

- name: Stop periphery service
  shell: |
    export XDG_RUNTIME_DIR="/run/user/$(id -u {{ komodo_user }})"
    systemctl --user stop periphery || true
  become: yes
  become_user: "{{ komodo_user }}"

- name: Remove old Komodo Periphery binary
  file:
    path: "{{ komodo_bin_path }}"
    state: absent
  become: yes
  when: komodo_bin_path is defined

- name: Ensure necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    mode: "0750"
  with_items:
    - "{{ komodo_bin_dir }}"
    - "{{ komodo_config_dir }}"
    - "{{ komodo_service_dir }}"

- name: Ensure SSL directory exists
  file:
    path: "/etc/komodo/ssl"
    state: directory
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    mode: "0750"
  become: yes
  when: ssl_enabled | default(true)

- name: Get release info from GitHub
  uri:
    url: "https://api.github.com/repos/{{ komodo_git_repo }}/releases/tags/{{ komodo_version }}"
    method: GET
    return_content: yes
  register: github_release_info

- name: Set correct download URL for architecture
  set_fact:
    komodo_bin_url: "{{ item.browser_download_url }}"
  with_items: "{{ github_release_info.json.assets }}"
  when: item.name is search(komodo_bin_override | default('periphery-' + ansible_architecture | default('periphery')))

- name: Fail if no matching binary is found
  fail:
    msg: "No matching binary found for architecture {{ ansible_architecture }} in version {{ komodo_version }}"
  when: komodo_bin_url is not defined

- name: Download Komodo {{ komodo_version }} Periphery Agent
  get_url:
    url: "{{ komodo_bin_url }}"
    dest: "{{ komodo_bin_path }}"
    mode: "0755"
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    force: yes

- name: Deploy configuration file
  template:
    src: periphery.config.toml.j2
    dest: "{{ komodo_config_path }}"
    mode: "0640"
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"

- name: Deploy systemd user service file
  template:
    src: periphery.service.j2
    dest: "{{ komodo_service_path }}"
    mode: "0644"
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"

- name: Reload systemd for {{ komodo_user }} user
  shell: |
    export XDG_RUNTIME_DIR="/run/user/$(id -u {{ komodo_user }})"
    systemctl --user daemon-reload
  become: yes
  become_user: "{{ komodo_user }}"

- name: Restart periphery service after update
  shell: |
    export XDG_RUNTIME_DIR="/run/user/$(id -u {{ komodo_user }})"
    systemctl --user restart periphery
  become: yes
  become_user: "{{ komodo_user }}"
